version: "3.9"
services:
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: asdf
        ports:
            - 5432:5432
        volumes:
            - /mnt/c/Users/patry/Desktop/praktyki/data:/var/lib/postgresql/data:z